### ISSUE TITLE
Absolute URLs in the list of posts

### ISSUE THREAD

**Issue by gp-dublincentral** [netlify-templates/one-click-hugo-cms#115]
If you have defined a `baseurl` in config.toml then https://github.com/netlify-templates/one-click-hugo-cms/blob/master/site/layouts/_default/li.html will write absolute URLs in the hrefs. 

Not wrong but makes testing across different environments trickier.

Is there a reason why `.Permalink` is being used instead of `.RelPermalink` to write the links?

**Comment by numbfall** [comment]
I have noticed this as well. On my other Hugo projects, setting `baseURL` does not affect `.Permalink` address. Hugo automatically swaps it to localhost addresses. 

My best guess is that this is a Hugo Server feature and one-click-hugo-cms is using gulp server and watch tasks instead of `hugo server` command.

Anyways, I use `.RelPermalink` in li.html and do not have any problems with it.

**Comment by erquhart** [comment]
Will take a PR for this 👍
