### ISSUE TITLE
Updating the build pipeline to include custom CMS templates for preview

### ISSUE THREAD

**Issue by maxcell** [netlify-templates/one-click-hugo-cms#678]
## Summary

Looks like when I upgraded all of our dependencies and fixed up some breaking changes in #674, I also broke the Preview Template feature. Fortunately this doesn't stop it from rendering properly once you've published your post in the editor, just need to find a way to bring the `src/js/cms.js` files into our `site/static/admin/index.html`.

| Current Preview | Current Output |
| :----: | :---: |
| ![CleanShot 2022-07-08 at 17 12 36](https://user-images.githubusercontent.com/8431042/178071096-62b51e56-e868-47ef-a093-baf08be3120d.png) | ![CleanShot 2022-07-08 at 17 29 42](https://user-images.githubusercontent.com/8431042/178072940-5de3386c-c8de-408f-9a49-e3d384da527b.png) |

### Steps to Reproduce

To reproduce this you need to go into the NetlifyCMS (`/admin`) and see any page or post.

### Expected Behavior

We should expect the current output as the current preview, with the same styling and everything we're using.

**Comment by cgc** [comment]
Seems like the issue might have been introduced in be22c5f6b329c9552f51cd63ece6108c58833d3e, which loads netlify-cms from unpkg instead of the included `cms.js` file:

```diff
--- a/src/cms.html
+++ b/site/static/admin/index.html
@@ -9,6 +9,6 @@
   <script src="https://identity-js.netlify.com/v1/netlify-identity-widget.js"></script>
 </head>
 <body>
-  <script src="<%= htmlWebpackPlugin.files.chunks.cms.entry %>"></script>
+  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
 </body>
 </html>
```

I was able to get a fix working on my site -- here are the changes pulled out into a commit https://github.com/cgc/one-click-hugo-cms/commit/97a313e84f0273dd71932c2efa168a05be0246b7. They deal with breaking changes in two packages:
- `date-fns` - format strings changed in 2.0, the release notes have a table of changes [here](https://github.com/date-fns/date-fns/blob/main/CHANGELOG.md#200---2019-08-20)
- `html-webpack-plugin` - `htmlWebpackPlugin.files` has a new format that disappointingly discards bundle names between 3.x and 4.x (documented in [project readme](https://github.com/jantimon/html-webpack-plugin), search for "`htmlWebpackPlugin.files`"). The change is a bit annoying because it means you have to assume the order of bundles. Since object property order is based on insertion order ([in ES6](https://2ality.com/2015/10/property-traversal-order-es6.html)), as long as that order is respected by webpack, the index in my commit is appropriate for the order of bundles in `webpack.common.js`. An issue to access bundles by name has been opened but is stale: https://github.com/jantimon/html-webpack-plugin/issues/1369.
