### ISSUE TITLE
formatting the css within paragraphs

### ISSUE THREAD

**Issue by swallowingspecialist** [netlify-templates/one-click-hugo-cms#79]
Am using the Netlify CMS which allows editing of the One-Click-Hugo-CMS with ease.

Am writing to find out if the issue is with the Netlify CMS or the One-Click-Hugo-cms that's messing with the formatting. 

eg. in this page https://www.speechtherapyworks.com.sg/values/ you can see the profile of the director but it appears a one long paragraph. But on the file it's already using markdown format. So either the Netlify CMS or the One-Click-Hugo-cms is "overiding" the formatting and only recognizing it as "<p>"

How should I trouble shoot to get the formatting done correctly?

**Comment by erquhart** [comment]
You're using the `text` widget rather than the `markdown` widget:

https://github.com/swallowingspecialist/hugo-repo-1/blob/bf8c57fb38d27514c63db6448a34af2481a973fe/site/static/admin/config.yml#L81

As a result, the output in your markdown is just plain text:

https://raw.githubusercontent.com/swallowingspecialist/hugo-repo-1/bf8c57fb38d27514c63db6448a34af2481a973fe/site/content/values/_index.md

Reach out in the Netlify CMS [community chat](https://gitter.im/netlify/netlifycms) if you need further help on this.
